### PR TITLE
add update user

### PR DESCRIPTION
**Pull request by DanielePalombo**
Hi we have add a reset password behavior and update function.

### CODE REVIEW

**Comment by fowlplay** [comment]
Any information when this pull request will be approved?
Added functionality would help in aligning angular-devise with Devise capabilities.
Looking forward to see this implemented in master branch.

**Comment by iamceege** [comment]
I agree with @fowlplay. These features would be extremely helpful. Any update on merging this in?

**Comment by RutujaKhandpekar** [comment]
What is the status of this pull request ? Or is there any other way to implement this ? This would be really helpful feature.

**Comment by hparfr** [comment]
I resolved conflicts between this branch and current master in https://github.com/hparfr/angular_devise/tree/refactor_daniel

I don't know if you should open a new PR here or https://github.com/DanielePalombo/angular_devise or somewhere else

**Comment by DanielePalombo** [comment]
@hparfr i think you need to create a new PR to cloudspace, after that i delete this PR.

**Comment by TheOneTheOnlyDavidBrown** [comment]
#74 rebased off of this. closing this one

**Pull request closed without merging**
