### PR TITLE
add password reset

### PR DESCRIPTION
**Pull request by hparfr**
It's a rebase of #24 (only implementation of password reset) with current master + a small improvement of the readme.

### CODE REVIEW

**Comment by hparfr** [comment]
It's password reset with some tests.
There is some place for improvement in the tests.
I did not merge "update" since it takes more time to test fully.

**Comment by colmben** [comment]
This PR doesn't work as it stands. The httpConfig calls are wrapping the creds with the default resource name of 'user'. But then httpConfig has code to check for a resource name and wraps again, so you get a request payload like user: { user: {email: ...}}

So the httpConfig calls should just send creds, not {user: creds}

**Comment by hparfr** [comment]
> So the httpConfig calls should just send creds, not {user: creds}
Fixed

**Comment by karensg** [comment]
Hi @hparfr , I am using your pull request, works as a charm. Thanks.
Too bad cloudspace is not supporting this library any more.

**Pull request merged**
